language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: CN0sj0DIOfwD229GPfRi0rJiolRIBMvIwElzDJOwS0HSuszJRFbK9RrZLZbfC0rGfDj/55HX7Byn4JBy//2wjmS8x8dhaEg66+biEZWKfhtvO8Q6aC0SAW3UupuGv2CqMr8aGNOjy7aRuChiuq2J3an6JEqOWlIECrSDMhskpAc=
  on:
    tags: true
    all_branches: trrue
    repo: bendrucker/hapi-bookshelf
